an:
  main_1_0: 21
ar:
  main_1_0: 11
be-BY:
  main_1_0: 24
bg-BG:
  main_1_0: 14
ca:
  main_1_0: 19
cmn:
  main_1_0: 9
cs:
  main_1_0: 48
da:
  main_1_0: 30
de:
  main_1_0: 91
el:
  main_1_0: 28
en-BE:
  main_1_0: 0
en-NL:
  main_1_0: 0
eo:
  main_1_0: 25
es:
  main_1_0: 93
es-AR:
  main_1_0: 0
fa-IR:
  main_1_0: 2
fi:
  main_1_0: 0
fr:
  main_1_0: 90
fr-BE:
  main_1_0: 0
ga-IE:
  main_1_0: 59
gl:
  main_1_0: 15
he:
  main_1_0: 13
he-IL: {}
hi:
  main_1_0: 0
hr:
  main_1_0: 6
hu:
  main_1_0: 30
id:
  main_1_0: 17
it:
  main_1_0: 64
it-CH:
  main_1_0: 0
it-IT: {}
ja:
  main_1_0: 18
km:
  main_1_0: 15
ko:
  main_1_0: 19
lt:
  main_1_0: 33
lv:
  main_1_0: 0
mi:
  main_1_0: 3
mk:
  main_1_0: 13
ml:
  main_1_0: 15
ml-IN:
  main_1_0: 0
nl: {}
nl-NL:
  main_1_0: 33
pl:
  main_1_0: 62
pt-BR:
  main_1_0: 92
pt-PT:
  main_1_0: 0
ro:
  main_1_0: 31
ru:
  main_1_0: 26
ru-RU: {}
sk:
  main_1_0: 21
sl:
  main_1_0: 27
sr:
  main_1_0: 90
sr-RS:
  main_1_0: 25
sv:
  main_1_0: 20
te:
  main_1_0: 9
tr:
  main_1_0: 27
uk:
  main_1_0: 100
ur:
  main_1_0: 0
ur-PK:
  main_1_0: 0
vi:
  main_1_0: 14
zh-TW:
  main_1_0: 100
